<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Insert into suppliers
        DB::table('suppliers')->insert([
            [
                'business_name' => 'PinoyBuild Construction',
                'business_address' => 'Pasig City',
                'contact_no' => '09171234567',
                'email_address' => 'contact@pinoybuild.ph',
                'tin' => '123-456-789-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH1234567890',
                'lbp_account_name' => 'PinoyBuild',
                'lbp_account_number' => '123456789012',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'MegaInfra',
                'business_address' => 'Cebu City',
                'contact_no' => '09181234567',
                'email_address' => 'infra@megainfra.com',
                'tin' => '234-567-890-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH2345678901',
                'lbp_account_name' => 'MegaInfra',
                'lbp_account_number' => '234567890123',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'LuzonTech Solutions',
                'business_address' => 'Quezon City',
                'contact_no' => '09191234567',
                'email_address' => 'contact@luzontech.ph',
                'tin' => '345-678-901-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH3456789012',
                'lbp_account_name' => 'LuzonTech',
                'lbp_account_number' => '345678901234',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'VisayasCater',
                'business_address' => 'Iloilo City',
                'contact_no' => '09171234568',
                'email_address' => 'sales@visayascater.ph',
                'tin' => '456-789-012-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH4567890123',
                'lbp_account_name' => 'VisayasCater',
                'lbp_account_number' => '456789012345',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Mindanao Events',
                'business_address' => 'Davao City',
                'contact_no' => '09181234568',
                'email_address' => 'info@mindanaoevents.ph',
                'tin' => '567-890-123-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH5678901234',
                'lbp_account_name' => 'Mindanao Events',
                'lbp_account_number' => '567890123456',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Pilipinas Transport',
                'business_address' => 'Makati City',
                'contact_no' => '09191234568',
                'email_address' => 'logistics@pilipinastranspo.ph',
                'tin' => '678-901-234-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH6789012345',
                'lbp_account_name' => 'Pilipinas Transpo',
                'lbp_account_number' => '678901234567',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Manila Office Supplies',
                'business_address' => 'Manila City',
                'contact_no' => '09171234569',
                'email_address' => 'contact@manilaofficesupplies.ph',
                'tin' => '789-012-345-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH7890123456',
                'lbp_account_name' => 'Manila Supplies',
                'lbp_account_number' => '789012345678',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'VisMin Consulting',
                'business_address' => 'Cagayan de Oro City',
                'contact_no' => '09181234569',
                'email_address' => 'consult@visminconsult.ph',
                'tin' => '890-123-456-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH8901234567',
                'lbp_account_name' => 'VisMin Consultants',
                'lbp_account_number' => '890123456789',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'HealthCare Philippines',
                'business_address' => 'Baguio City',
                'contact_no' => '09191234569',
                'email_address' => 'info@healthcareph.ph',
                'tin' => '901-234-567-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH9012345678',
                'lbp_account_name' => 'HealthCare PH',
                'lbp_account_number' => '901234567890',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Luzon Energy Solutions',
                'business_address' => 'Batangas City',
                'contact_no' => '09171234570',
                'email_address' => 'contact@luzonenergy.ph',
                'tin' => '012-345-678-000',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH0123456789',
                'lbp_account_name' => 'Luzon Energy',
                'lbp_account_number' => '012345678901',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'SafeGuard Security',
                'business_address' => 'Taguig City',
                'contact_no' => '09181234570',
                'email_address' => 'security@safeguardsecurity.ph',
                'tin' => '123-456-789-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH1234567891',
                'lbp_account_name' => 'SafeGuard Security',
                'lbp_account_number' => '123456789123',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'PinoyPromo Agency',
                'business_address' => 'Mandaluyong City',
                'contact_no' => '09191234570',
                'email_address' => 'marketing@pinoypromo.ph',
                'tin' => '234-567-890-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH2345678902',
                'lbp_account_name' => 'PinoyPromo',
                'lbp_account_number' => '234567890234',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'EduCare Training Center',
                'business_address' => 'Legazpi City',
                'contact_no' => '09171234571',
                'email_address' => 'training@educare.ph',
                'tin' => '345-678-901-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH3456789013',
                'lbp_account_name' => 'EduCare Training',
                'lbp_account_number' => '345678901345',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Tropics Hospitality',
                'business_address' => 'Puerto Princesa',
                'contact_no' => '09181234571',
                'email_address' => 'hospitality@tropicshospitality.ph',
                'tin' => '456-789-012-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH4567890124',
                'lbp_account_name' => 'Tropics Hospitality',
                'lbp_account_number' => '456789012456',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'GreenPinoy Solutions',
                'business_address' => 'Los Baños',
                'contact_no' => '09191234571',
                'email_address' => 'sustainability@greenpinoy.ph',
                'tin' => '567-890-123-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH5678901235',
                'lbp_account_name' => 'GreenPinoy',
                'lbp_account_number' => '567890123567',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Bayanihan Outreach',
                'business_address' => 'Zamboanga City',
                'contact_no' => '09171234572',
                'email_address' => 'community@bayanihan.ph',
                'tin' => '678-901-234-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH6789012346',
                'lbp_account_name' => 'Bayanihan Outreach',
                'lbp_account_number' => '678901234678',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Vigilant Guard Services',
                'business_address' => 'Caloocan City',
                'contact_no' => '09181234572',
                'email_address' => 'security@vigilantguard.ph',
                'tin' => '789-012-345-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH7890123457',
                'lbp_account_name' => 'Vigilant Guard',
                'lbp_account_number' => '789012345678',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'business_name' => 'Elite Security Solutions',
                'business_address' => 'General Santos City',
                'contact_no' => '09191234572',
                'email_address' => 'info@elitesecurity.ph',
                'tin' => '890-123-456-001',
                'vat' => true,
                'nvat' => false,
                'philgeps_reg_no' => 'PH8901234568',
                'lbp_account_name' => 'Elite Security',
                'lbp_account_number' => '890123456789',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // Insert into supplier_categories
        DB::table('supplier_categories')->insert([
            ['supplier_id' => 1, 'category_id' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 2, 'category_id' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 3, 'category_id' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 4, 'category_id' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 5, 'category_id' => 3, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 6, 'category_id' => 3, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 7, 'category_id' => 4, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 8, 'category_id' => 4, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 9, 'category_id' => 5, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 10, 'category_id' => 5, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 11, 'category_id' => 6, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 12, 'category_id' => 6, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 13, 'category_id' => 7, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 14, 'category_id' => 7, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 15, 'category_id' => 8, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 16, 'category_id' => 8, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 17, 'category_id' => 9, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 18, 'category_id' => 9, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 5, 'category_id' => 10, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 12, 'category_id' => 10, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 13, 'category_id' => 11, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 6, 'category_id' => 11, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 7, 'category_id' => 12, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 9, 'category_id' => 12, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 10, 'category_id' => 13, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 15, 'category_id' => 13, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 8, 'category_id' => 14, 'created_at' => $now, 'updated_at' => $now],
            ['supplier_id' => 16, 'category_id' => 14, 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}